export const QUOTES: string[] = [
  "Do the chore. Be the legend.",
  "Tiny jobs. Big wins.",
  "Future you says thanks.",
  "Clean room, clear brain.",
  "Effort counts even on tired days.",
  "You can do hard things.",
  "One task at a time.",
  "Start now. Brag later.",
  "Momentum beats motivation.",
  "Done is powerful.",
  "Win the next small play.",
  "Great teams clean up after themselves.",
  "Do your job, then help the team.",
  "Effort is the first stat coaches notice.",
  "Hustle counts at home too.",
  "Good teammates do the unseen work.",
  "Stack wins like a playoff run.",
  "Play through the chore.",
  "Your room is your practice field.",
  "Coach would call this accountability.",
  "Little reps make big players.",
  "Be coachable. Start now.",
  "Defense wins games. Dishes win peace.",
  "Finish the drill.",
  "Every champion starts with discipline.",
  "Do the basics like they matter.",
  "The scoreboard likes follow-through.",
  "Work like the scout is watching.",
  "Make the easy play.",
  "Train your habits.",
  "Control what you can control.",
  "Next play mentality. Next chore done.",
  "Accountability is undefeated.",
  "Small disciplines make big seasons.",
  "Every rep is a vote for who you are.",
  "Clean hands, clean room, clean win.",
  "No one wins alone.",
  "Handle your assignment.",
  "Leave it better than you found it.",
  "Own your zone.",
  "Run the play.",
  "The little things are the big things.",
  "Do your part of the game plan.",
  "Everybody eats when everybody helps.",
  "Be elite at ordinary things.",
  "The best ability is reliability.",
  "Your family is your first team.",
  "Make the next right play.",
  "Start fast. Finish clean.",
  "Chores are conditioning for character.",
  "Your future coach likes this habit.",
  "Own the fourth quarter.",
  "Every dynasty has chores.",
  "Lead with action.",
  "Coach says: less talk, more effort.",
  "Standards do not take days off.",
  "Energy, effort, execution.",
  "Home-field advantage starts with chores.",
  "Every chore is a leadership rep.",
  "Great captains serve first.",
  "Lock in for ten minutes.",
  "Earn the green tile.",
  "Make your tile proud.",
  "The board does not lie.",
  "Points are waiting.",
  "Turn red into green.",
  "Be the kid who gets it done.",
  "Short chore, big relief.",
  "Do it before someone asks twice.",
  "Clean space, clear head, better game.",
  "Be a finisher.",
  "Your habits are training.",
  "Do not let lazy call the plays.",
  "Run your route.",
  "Stick the landing.",
  "Make the simple play simple.",
  "Finish the possession.",
  "Outlast the mess.",
  "Be consistent, not dramatic.",
  "Stay sharp at home.",
  "Your effort makes the house better.",
  "Do the small thing with big energy.",
  "Make home feel like a win.",
  "Great days start with responsibility.",
  "Work quietly. Win loudly.",
  "Put points on the board.",
  "Do your chores like a starter.",
  "Give championship effort.",
  "Reliable beats talented when talented skips chores.",
  "Clean fast, then relax slow.",
  "The best teams do not need reminders.",
  "Be reminder-proof.",
  "Execute without eye rolls.",
  "Help the house win.",
  "Every family needs glue players.",
  "Be the glue.",
  "Respect the grind.",
  "Do the ordinary with pride.",
  "Make the task tap out.",
  "That pile has no defense.",
  "Do not let dishes go on a run.",
  "Call timeout on clutter.",
  "Reset the scoreboard.",
  "Make the comeback.",
  "Start the streak.",
  "Protect the streak.",
  "All effort counts.",
  "No wasted reps.",
  "Every clean dish is a point.",
  "Make the next 15 minutes count.",
  "Do it now, celebrate later.",
  "Turn effort into freedom.",
  "Small chores, big scoreboard.",
  "Be a clutch cleaner.",
  "The clutch gene includes dishes.",
  "Good habits win close games.",
  "Close the gap.",
  "Be where your feet are.",
  "Win your shift.",
  "Short shifts. High effort.",
  "Clean like it is your contract year.",
  "Do not get outworked by a laundry basket.",
  "Prove it with action.",
  "Keep your standards high.",
  "Handle the fundamentals.",
  "First touch matters. First chore too.",
  "Be quick, not careless.",
  "Quality reps matter.",
  "Be proud of boring excellence.",
  "Make responsibility normal.",
  "Do the job right once.",
  "Be the calm in the chaos.",
  "Turn chaos into order.",
  "Put the team first.",
  "Be dependable at home.",
  "Earn trust with follow-through.",
  "Do the chore and move on.",
  "Nobody regrets finishing early.",
  "Green tiles are earned.",
  "Clean now, complain never.",
  "Good teams finish the details.",
  "The little job is still your job.",
  "Responsibility is a muscle.",
  "Train the muscle.",
  "Start with one thing.",
  "Do not wait for perfect energy.",
  "Be useful right now.",
  "Make the house lighter.",
  "Your effort lowers the noise.",
  "Clean work is quiet leadership.",
  "Be the standard.",
  "Coach voice: finish strong.",
  "Captain voice: help out.",
  "Teammate voice: I got it.",
  "Winner voice: done.",
  "Do the work. Keep the peace.",
  "Your space reflects your standard.",
  "Make your future self fist pump.",
  "Turn the chore into a quick win.",
  "Get in, get it done, get out.",
  "Less delay, more done.",
  "Make your move.",
  "Do not overthink the obvious.",
  "Make boring look easy.",
  "Win the hidden scoreboard.",
  "Be solid in the small moments.",
  "Clean is a competitive advantage.",
  "Champions pick up after practice.",
  "Family MVPs do chores.",
  "The assist matters as much as the goal.",
  "Score one for the house.",
  "Make the play your family needs.",
  "Do not wait for the whistle.",
  "Own the task.",
  "Bring the effort.",
  "Leave excuses on the bench.",
  "Your house team needs you.",
  "Turn hustle into help.",
  "Responsibility wins championships.",
  "Be ready, be willing, be done.",
  "Good teammates notice what needs doing.",
  "Spot the mess. Make the play.",
  "Clean it like a captain.",
  "One chore closer.",
  "Nobody is too good for dishes.",
  "Take pride in the basics.",
  "Basics beat chaos.",
  "Make the habit automatic.",
  "Strong habits, strong kid.",
  "Get your reps before screen time.",
  "Earn the chill.",
  "Be the reason the tile turns green.",
  "Chores are just drills for life.",
  "Do not let the scoreboard stay at zero.",
  "Put up numbers.",
  "Your effort counts today.",
  "Make it happen.",
  "Go be useful.",
  "Hard work beats the mess.",
  "Discipline is doing it before being asked.",
  "Your effort is your signature.",
  "Greatness loves clean floors.",
  "Lead by helping.",
  "Clean spaces make room for good days.",
  "The work nobody sees still matters.",
  "Small wins build big confidence.",
  "Choose action over delay.",
  "Today\u2019s effort becomes tomorrow\u2019s habit.",
  "Do the next useful thing.",
  "Be proud of your follow-through.",
  "Finish like it matters.",
  "Make your home team better.",
  "Winning starts with ownership.",
  "Good habits are built quietly.",
  "Be the reliable one.",
  "Every completed task is momentum.",
  "Chores are teamwork in disguise.",
  "The house gets better when you help.",
  "Show up for the small stuff.",
  "Effort turns chores into wins.",
  "Handle the ball. Handle the chore.",
  "The best players do the basics.",
  "Championship homes need role players.",
  "Do your part before the buzzer.",
  "Every assist counts.",
  "Small jobs, strong character.",
  "Practice responsibility daily.",
  "Good choices stack up.",
  "Make today easier for everyone.",
  "Your effort has an impact.",
  "Get it done and move forward.",
  "Quiet effort still counts.",
  "Be someone people can count on.",
  "Clean it because you live here.",
  "Respect the space. Respect the team.",
  "The next win is one task away.",
  "Be the reason things run smoother.",
  "Work first. Chill after.",
  "Your future self appreciates hustle.",
  "Make the responsible choice.",
  "Done feels better than delayed.",
  "Do the work while it is small.",
  "Do not let small messes become big problems.",
  "Good teammates clean up.",
  "Help without making it a show.",
  "Turn responsibility into a habit.",
  "Every home needs finishers.",
  "Be a finisher today.",
  "Make the simple things excellent.",
  "Effort is always available.",
  "Win the minute in front of you.",
  "Small actions create trust.",
  "Do your work with pride.",
  "Make ordinary effort extraordinary.",
  "Every chore is a chance to lead.",
  "Get the job done clean.",
  "Be quick. Be kind. Be useful.",
  "Great teams share the load.",
  "Make the house easier to live in.",
  "Your attitude is part of the chore.",
  "Responsibility is a quiet superpower.",
  "Start small, finish strong.",
  "Good habits travel everywhere.",
  "The best time to help is now.",
  "Take the first step.",
  "Clean spaces create calm minds.",
  "Help first, celebrate second.",
  "Every task done is one less problem.",
  "Be the teammate your family needs.",
  "Do not wait for motivation.",
  "Action creates motivation.",
  "Reset the room. Reset the day.",
  "Your effort makes a difference.",
  "Make the responsible thing normal.",
  "Small wins are still wins.",
  "Stack good choices.",
  "Be proud of being dependable.",
  "The house wins when everyone helps.",
  "Do it once. Do it right.",
  "Be strong in the boring moments.",
  "Make your mark with effort.",
  "Finish the list. Win the day.",
  "Good work is never wasted.",
  "Be useful before being asked.",
  "Every helper matters.",
  "Take care of your space.",
  "Turn chores into points.",
  "Make the dashboard happy.",
  "Bring the green energy.",
  "Win the home game.",
  "Chores are part of the team sport.",
  "Put the family on your back for ten minutes.",
  "The clean-up crew wins too.",
  "Get your points. Earn your peace.",
  "Make the board tell a good story.",
  "Good teams communicate and clean.",
  "Be steady. Be helpful. Be done.",
  "Your chore is your contribution.",
  "Handle business.",
  "Get in the game.",
  "Do the work that helps everybody.",
  "Every responsibility completed builds trust.",
  "Make it clean enough to be proud of.",
  "Start with what is in front of you.",
  "Win by finishing.",
  "Green tiles love effort.",
  "Be the kid who follows through.",
  "No drama. Just done.",
  "Put in the work.",
  "Make it easier for the next person.",
  "Do the right thing while it is easy.",
  "Strong families share the load.",
  "Make your effort obvious.",
  "Today\u2019s chore is tomorrow\u2019s freedom.",
  "Be reliable on purpose.",
  "Clean it, log it, move on.",
  "Let your actions speak.",
  "Finish the play.",
  "Keep the household moving.",
  "Be a low-maintenance legend.",
  "Win the boring stuff.",
  "Do the little things without being chased.",
  "Be helpful with no scoreboard needed.",
  "Good habits beat reminders.",
  "Make the next minute count.",
  "Your chores are part of your character.",
  "Everything counts when everyone helps.",
  "Make it happen before screen time.",
  "Help hard. Play hard.",
  "Done is better than almost.",
  "Be proud of being useful.",
  "Clean up like a champion.",
  "Work like your team depends on it.",
  "Your home team does depend on it.",
  "Make the responsible play.",
  "Own your contribution.",
  "Every effort lifts the room.",
  "Do the next chore like it matters.",
  "Win the day at home.",
  "Finish strong, even on chores."
];
